"""Add enhanced task model with completion tracking and rewards

Revision ID: 428e4fd66675
Revises: add_match_requests_table
Create Date: 2025-08-06 01:23:06.176017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428e4fd66675'
down_revision = 'add_match_requests_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='taskdifficulty'), nullable=True))
    op.add_column('tasks', sa.Column('category', sa.Enum('SOCIAL', 'CREATIVE', 'PHYSICAL', 'MENTAL', 'BONDING', name='taskcategory'), nullable=True))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at_user1', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completed_at_user2', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('progress_percentage', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('submission_count', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('base_coin_reward', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('difficulty_multiplier', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('final_coin_reward', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('requires_validation', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('validation_submitted', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('validation_approved', sa.Boolean(), nullable=True))
    op.drop_column('tasks', 'coin_reward')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('coin_reward', sa.INTEGER(), nullable=True))
    op.drop_column('tasks', 'validation_approved')
    op.drop_column('tasks', 'validation_submitted')
    op.drop_column('tasks', 'requires_validation')
    op.drop_column('tasks', 'final_coin_reward')
    op.drop_column('tasks', 'difficulty_multiplier')
    op.drop_column('tasks', 'base_coin_reward')
    op.drop_column('tasks', 'submission_count')
    op.drop_column('tasks', 'progress_percentage')
    op.drop_column('tasks', 'completed_at_user2')
    op.drop_column('tasks', 'completed_at_user1')
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'difficulty')
    # ### end Alembic commands ### 